# Generated by Django 3.0.2 on 2020-01-04 22:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import domotic.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', domotic.models.HexField(length=1, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2), django.core.validators.RegexValidator('^[0-9a-f]*$', 'Seuls 0-9 et a-f sont autorisés'), django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2), django.core.validators.RegexValidator('^[0-9a-f]*$', 'Seuls 0-9 et a-f sont autorisés'), django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2), django.core.validators.RegexValidator('^[0-9a-f]*$', 'Seuls 0-9 et a-f sont autorisés')], verbose_name='Extrémité')),
                ('cluster', domotic.models.HexField(length=2, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4), django.core.validators.RegexValidator('^[0-9a-f]*$', 'Seuls 0-9 et a-f sont autorisés'), django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4), django.core.validators.RegexValidator('^[0-9a-f]*$', 'Seuls 0-9 et a-f sont autorisés'), django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4), django.core.validators.RegexValidator('^[0-9a-f]*$', 'Seuls 0-9 et a-f sont autorisés')], verbose_name='Groupe')),
                ('number', domotic.models.HexField(length=2, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4), django.core.validators.RegexValidator('^[0-9a-f]*$', 'Seuls 0-9 et a-f sont autorisés'), django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4), django.core.validators.RegexValidator('^[0-9a-f]*$', 'Seuls 0-9 et a-f sont autorisés'), django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4), django.core.validators.RegexValidator('^[0-9a-f]*$', 'Seuls 0-9 et a-f sont autorisés')], verbose_name='Numéro')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('unit', models.CharField(blank=True, max_length=100, verbose_name='Unité')),
                ('exponent', models.IntegerField(default=0, verbose_name='Exposant')),
            ],
            options={
                'verbose_name': 'Attribut',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('address', domotic.models.HexField(length=2, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4), django.core.validators.RegexValidator('^[0-9a-f]*$', 'Seuls 0-9 et a-f sont autorisés'), django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4), django.core.validators.RegexValidator('^[0-9a-f]*$', 'Seuls 0-9 et a-f sont autorisés'), django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4), django.core.validators.RegexValidator('^[0-9a-f]*$', 'Seuls 0-9 et a-f sont autorisés')], verbose_name='Adresse')),
                ('mac', domotic.models.HexField(blank=True, length=4, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8), django.core.validators.RegexValidator('^[0-9a-f]*$', 'Seuls 0-9 et a-f sont autorisés'), django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8), django.core.validators.RegexValidator('^[0-9a-f]*$', 'Seuls 0-9 et a-f sont autorisés'), django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8), django.core.validators.RegexValidator('^[0-9a-f]*$', 'Seuls 0-9 et a-f sont autorisés')], verbose_name='Adresse MAC')),
            ],
            options={
                'verbose_name': 'Appareil',
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Horodatage')),
                ('value', models.IntegerField(verbose_name='Valeur')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domotic.Attribute', verbose_name='Attribut')),
            ],
            options={
                'verbose_name': 'Valeur',
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domotic.Device', verbose_name='Appareil'),
        ),
    ]
